version: "2"
services:
  database:
    image: postgres:14.6-alpine
    restart: always
    environment:
      - POSTGRES_DB=teamifydb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d teamifydb'"]
      interval: 10s
      timeout: 3s
      retries: 3
    # volumes:
    #   - ./database:/var/lib/postgresql/data

  server:
    build: ./server
    # env_file:
    #   - ./server/.env
    ports:
      - "8000:8000"
    depends_on:
      - database
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: teamifydb
    volumes:
      - ./server:/server
    command: ash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  web:
    build: ./web
    ports:
      - "3000:3000"
    depends_on:
      - server
    volumes:
      - ./web:/web
    command: "yarn dev"

volumes:
  db:
    driver: local
